apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"utilitiesoperator-serving-cert","namespace":"funcom-operators"},"spec":{"dnsNames":["utilitiesoperator-webhook-svc.funcom-operators.svc","utilitiesoperator-webhook-svc.funcom-operators.svc.cluster.local"],"issuerRef":{"kind":"Issuer","name":"operators-selfsigned-issuer"},"secretName":"utilitiesoperator-webhook-server-cert"}}
  name: utilitiesoperator-serving-cert
  namespace: funcom-operators
spec:
  dnsNames:
  - utilitiesoperator-webhook-svc.funcom-operators.svc
  - utilitiesoperator-webhook-svc.funcom-operators.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: operators-selfsigned-issuer
  secretName: utilitiesoperator-webhook-server-cert
