apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"databaseoperator-proxy-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"operators-proxy-role"},"subjects":[{"kind":"ServiceAccount","name":"databaseoperator-controller-manager","namespace":"funcom-operators"}]}
  name: databaseoperator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operators-proxy-role
subjects:
- kind: ServiceAccount
  name: databaseoperator-controller-manager
  namespace: funcom-operators
