apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"battlegroupoperator-manager-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"battlegroupoperator-manager-role"},"subjects":[{"kind":"ServiceAccount","name":"battlegroupoperator-controller-manager","namespace":"funcom-operators"}]}
  name: battlegroupoperator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: battlegroupoperator-manager-role
subjects:
- kind: ServiceAccount
  name: battlegroupoperator-controller-manager
  namespace: funcom-operators
