# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     deployment.kubernetes.io/revision: "2"
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.8.0"},"name":"cert-manager-webhook","namespace":"cert-manager"},"spec":{"replicas":0,"selector":{"matchLabels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook"}},"template":{"metadata":{"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.8.0"}},"spec":{"containers":[{"args":["--v=2","--secure-port=10250","--dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)","--dynamic-serving-ca-secret-name=cert-manager-webhook-ca","--dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"quay.io/jetstack/cert-manager-webhook:v1.8.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/livez","port":6080,"scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"cert-manager","ports":[{"containerPort":10250,"name":"https","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":6080,"scheme":"HTTP"},"initialDelaySeconds":5,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"securityContext":{"allowPrivilegeEscalation":false}}],"nodeSelector":{"kubernetes.io/os":"linux","node.funcom.com/workload":"infrastructure"},"securityContext":{"runAsNonRoot":true},"serviceAccountName":"cert-manager-webhook","tolerations":[{"key":"node.funcom.com/infrastructure","operator":"Exists"},{"key":"node-role.kubernetes.io/master","operator":"Exists"}]}}}}
#   labels:
#     app: webhook
#     app.kubernetes.io/component: webhook
#     app.kubernetes.io/instance: cert-manager
#     app.kubernetes.io/name: webhook
#     app.kubernetes.io/version: v1.8.0
#   name: cert-manager-webhook
#   namespace: cert-manager
#   resourceVersion: "294277"
#   uid: 0491d807-0d5e-42e5-abac-5d702c7977d6
# spec:
#   progressDeadlineSeconds: 600
#   replicas: 1
#   revisionHistoryLimit: 10
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: webhook
#       app.kubernetes.io/instance: cert-manager
#       app.kubernetes.io/name: webhook
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: webhook
#         app.kubernetes.io/component: webhook
#         app.kubernetes.io/instance: cert-manager
#         app.kubernetes.io/name: webhook
#         app.kubernetes.io/version: v1.8.0
#     spec:
#       containers:
#       - args:
#         - --v=2
#         - --secure-port=10250
#         - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
#         - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
#         - --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
#         env:
#         - name: POD_NAMESPACE
#           valueFrom:
#             fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.namespace
#         image: quay.io/jetstack/cert-manager-webhook:v1.8.0
#         imagePullPolicy: IfNotPresent
#         livenessProbe:
#           failureThreshold: 3
#           httpGet:
#             path: /livez
#             port: 6080
#             scheme: HTTP
#           initialDelaySeconds: 60
#           periodSeconds: 10
#           successThreshold: 1
#           timeoutSeconds: 1
#         name: cert-manager
#         ports:
#         - containerPort: 10250
#           name: https
#           protocol: TCP
#         readinessProbe:
#           failureThreshold: 3
#           httpGet:
#             path: /healthz
#             port: 6080
#             scheme: HTTP
#           initialDelaySeconds: 5
#           periodSeconds: 5
#           successThreshold: 1
#           timeoutSeconds: 1
#         resources: {}
#         securityContext:
#           allowPrivilegeEscalation: false
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext:
#         runAsNonRoot: true
#       serviceAccount: cert-manager-webhook
#       serviceAccountName: cert-manager-webhook
#       terminationGracePeriodSeconds: 30