apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/battlegroupoperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/battlegroupoperator-serving-cert"},"name":"battlegroupoperator-mutating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"battlegroupoperator-webhook-svc","namespace":"funcom-operators","path":"/mutate-igw-funcom-com-v1-battlegroup"}},"failurePolicy":"Fail","name":"mbattlegroup.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE"],"resources":["battlegroups"]}],"sideEffects":"None"}]}
  name: battlegroupoperator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: battlegroupoperator-webhook-svc
      namespace: funcom-operators
      path: /mutate-igw-funcom-com-v1-battlegroup
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mbattlegroup.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - battlegroups
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
