apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/battlegroupoperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/battlegroupoperator-serving-cert"},"name":"battlegroupoperator-mutating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"battlegroupoperator-webhook-svc","namespace":"funcom-operators","path":"/mutate-igw-funcom-com-v1-battlegroup"}},"failurePolicy":"Fail","name":"mbattlegroup.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE"],"resources":["battlegroups"]}],"sideEffects":"None"}]}
  name: battlegroupoperator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lRVkMyenR0Q0RHekkyUmpldzh4WkFHREFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTJNRGN5TlRBNE1qSXhOVm9YRFRJMk1UQXlNekE0TWpJeE5Wb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3o3OWxRcTRlRzEyVExRT29yMW51bkluT3FIOHhRczVqQXlOLzlaClE2RWF6RFVha0FwckluNlpNQ1JzQ2xWYU03VVN4Z0c1azBObnVFeEd1OXUyTXgxN2ZPb3FhNHFkN2MzQ1NCUjgKMnFaeUVXY2JJNzlMQUNsOWl5bUJNdFdKbzBFRjlEK1JKWC9JemtPMVIrRUxnVEJ5ZFcwSEZRcm8vRml5Z3RSTwp2YXFiaHFieFg2aVQyTnh5TFZ1NHhwTWxHelVpcWxWc2M2aC9uenIxQzJhZS9DMkN0WlRjUGJDMDUyQ1F6U3pxCktTRUVwV0lOTFNFVDdqQUd5WFNsTzV6YlNaMEpUaG9YZ1lmaGtpZVpraXBnemZiWGY5TCtIY1lvdHI5Q3I1RTgKaWZLbzkvTUpEWW9CTG9IK09kSUxGN2JJRmZMM0VXcjhIeWMrbjZtZXI2MWd2b2NDQXdFQUFhT0JxakNCcHpBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBRENCaGdZRFZSMFJBUUgvQkh3d2VvSTBZbUYwCmRHeGxaM0p2ZFhCdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhOMll5NW1kVzVqYjIwdGIzQmxjbUYwYjNKekxuTjIKWTRKQ1ltRjBkR3hsWjNKdmRYQnZjR1Z5WVhSdmNpMTNaV0pvYjI5ckxYTjJZeTVtZFc1amIyMHRiM0JsY21GMApiM0p6TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBbHY4RHRFT3dvCnBHMURCejIza0xOZWEwZWRQSm9RQjlNMHRzOEl4NDh2Y0VHNVRiQ25Vc1JwdHlIOGlUakNnQ3BhVUJpV25Xd04KbFV4QzhVdGI2M3IvWTJtZlFNNDJsYnZDQU40Q2xISnBHMVJLSGRoZ3FGcWh4R3doU0ZaaE1WdDRxVVdQclNPRApScFo4elRHL0QwUEprNVY0WGt0NFZEK0VmNUNDQ3o5OERqZkZOM2JHYVpkVi95dWtZVmZzMDZaNVVoU3VybVNHCmFlSUNUOHdESXFqWEJRYmFPc0o0c2ZWQkpjU3hHSndOVzJ6QzM4Z2c4YWc0dlZQTGVubExZdEdwY3h1L3ZIMWsKbmxCSDllelJSRzhUem00WmlPV3JCZWhaUWZWQ1czckwyUlhaS3NCdy81cFRrYVFHU3VLRXNNcFZXb0lscHVWSQo2SnIyWEluQmlEeTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: battlegroupoperator-webhook-svc
      namespace: funcom-operators
      path: /mutate-igw-funcom-com-v1-battlegroup
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mbattlegroup.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - battlegroups
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
