apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/utilitiesoperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/utilitiesoperator-serving-cert"},"name":"utilitiesoperator-mutating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"utilitiesoperator-webhook-svc","namespace":"funcom-operators","path":"/mutate-igw-funcom-com-v1-imagepreheat"}},"failurePolicy":"Fail","name":"mimagepreheat.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE"],"resources":["imagepreheats"]}],"sideEffects":"None"}]}
  name: utilitiesoperator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lRYXBxVERqNWcxbDhNOUlnU3AyaEpGVEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTJNRGN5TlRBNE1qSXhObG9YRFRJMk1UQXlNekE0TWpJeE5sb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTW9kS0RnekI2MGcvTzl1aU1XOFlBYllJdTNaWGJ1ODBuOWNOeGlQClgzZ05JUnozRkZDeWk2NFFTeTNMcEpDWUVpRDVLOFBKMys0MHJqNmlMaWVQMDRZK0FIR2xwTGswOFdSTjdnd2cKTWRGcXNKRi9hdVI5R3BqMkZjdVpka0JzazYzSjdUOTEwcno1V0MzM3FjMVkwUWExbVRPQ2IvM3lMTklibkh3Lwo2OXFpZ2gyTWx1UVg1bkdMRDNHa0lpeDRaZDFjNXNNeUhnbzV0OVh3elFBZ3VpM1Y0SXdOZkVUY09yaVpWZEwzCk4rYzJDRm9FWjYzTDR4OENkNFVFK29EQ2RWL2VQY1lnUDQxNkZzejVLaUNGaUJtUXcvdXUrWEpWLzhFTjY0ajUKMUthUFlaenN1eGdGdUR1TDZYSytMK0MxdGVoalcwdGpxQU4zKytyWmtualFlSU1DQXdFQUFhT0JwakNCb3pBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBRENCZ2dZRFZSMFJBUUgvQkhnd2RvSXlkWFJwCmJHbDBhV1Z6YjNCbGNtRjBiM0l0ZDJWaWFHOXZheTF6ZG1NdVpuVnVZMjl0TFc5d1pYSmhkRzl5Y3k1emRtT0MKUUhWMGFXeHBkR2xsYzI5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzNaakxtWjFibU52YlMxdmNHVnlZWFJ2Y25NdQpjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQllXM0loeEJJM21mRUs4CkNxeklvUnBXMXlqdlhVNXYvTHF6VTBBMGJxS2s2NVhLZ2RUMGRZRVJKaTFXOVhxaW85M3hCVE5lVlRTRHVhM1YKT1hiZHlkUWE0djJ2RnBwcXNMUlBidWZSK051VTE1TVpKVlB0QWptMlZNckwvOU5PK3d0bitRcWxrODB4cEJTWgozWTNEc2p6b3JUekliRlFHeUt1TXJ6RXJORWJGbEFTOWVmWWt0TWtiZHc1OU9iV2dWK215UEMxMEp0eFFJMDZtCmM3U3djb2pxNmtYVmdQR2RRNHBTcVNRTDhhVGJmbUZuTDBMLzcyVlNDMTQxcFBXblk4UEY1b2h0SU02MkJubkUKeTlXZzJYSVhJYk9sK3hpREpZdWVFSlNqazF4N1BwOUZVTzdab0JBaXpibnpLZFJjRW9XdDdlWE1yYzJKZjd4OQpGTFlOSlY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: utilitiesoperator-webhook-svc
      namespace: funcom-operators
      path: /mutate-igw-funcom-com-v1-imagepreheat
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mimagepreheat.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imagepreheats
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
