apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"control-plane":"database-controller-manager"},"name":"databaseoperator-controller-manager-metrics-svc","namespace":"funcom-operators"},"spec":{"ports":[{"name":"https","port":8443,"protocol":"TCP","targetPort":"https"}],"selector":{"control-plane":"database-controller-manager"}}}
  labels:
    control-plane: database-controller-manager
  name: databaseoperator-controller-manager-metrics-svc
  namespace: funcom-operators
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: database-controller-manager