apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/serveroperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/serveroperator-serving-cert"},"name":"serveroperator-validating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"serveroperator-webhook-svc","namespace":"funcom-operators","path":"/validate-igw-funcom-com-v1-servergroup"}},"failurePolicy":"Fail","name":"vservergroup.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE","DELETE"],"resources":["servergroups"]}],"sideEffects":"None"}]}
  name: serveroperator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: serveroperator-webhook-svc
      namespace: funcom-operators
      path: /validate-igw-funcom-com-v1-servergroup
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vservergroup.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - servergroups
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
