apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/serveroperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/serveroperator-serving-cert"},"name":"serveroperator-validating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"serveroperator-webhook-svc","namespace":"funcom-operators","path":"/validate-igw-funcom-com-v1-servergroup"}},"failurePolicy":"Fail","name":"vservergroup.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE","DELETE"],"resources":["servergroups"]}],"sideEffects":"None"}]}
  name: serveroperator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRWVE0Qy9WYXZtQWFIT0lwUDRjQmRtakFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTJNRGN5TlRBNE1qSXhOVm9YRFRJMk1UQXlNekE0TWpJeE5Wb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGZYVUtnSUdJeEFNOVFENHBFaVNLK2o2eGRNMFJlUGdWaTRxVHBnCnEwSEJ4SDR0NlVlcE1GS1hOcytFTnFWNTQvaUNLS0ZEY2hvRVFNaEpuR3JFTDFKTm5hU2RyMTBoTFNQd2k5QlUKTSswZW01S3lUK2tmVnhLZUxwUHhpUmpjZ2svM2tDdnc1WDNEWW5xaXI4OGIrNXVBZE1zMUhxSUphb21uR0t2cwprNzY1bm9ybE4vZFM2eW5iVEpNeWRCNU1ZdzRKdTB0UXpFYXZqOFh6dnZRRU0vV2llOGNPRDEvZkorclY4UEw1CjVLZkk4a1hzM3FrVFJ0OERaZTlFVWU0Q2FvOEtibGRFd3VRVXkwVncwQmtGVEJmeXk2S0ZDUVNoc2lEQ214VnUKWHY4eVdYamlhSThPV29wbnA4MkZ1eENGbmJnek9oeFg1Q1ZLcU5oNlg4Z29yUEVDQXdFQUFhT0JuekNCbkRBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBREI4QmdOVkhSRUJBZjhFY2pCd2dpOXpaWEoyClpYSnZjR1Z5WVhSdmNpMTNaV0pvYjI5ckxYTjJZeTVtZFc1amIyMHRiM0JsY21GMGIzSnpMbk4yWTRJOWMyVnkKZG1WeWIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxemRtTXVablZ1WTI5dExXOXdaWEpoZEc5eWN5NXpkbU11WTJ4MQpjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaUszdURoaG1PRjRoVlV0SWViYWFnblpsCi9qcXM5YTdHQW5oNWY2MUUydjZXSmZUV3J5MWFRL21UWG53cDBsS2hjanRIL21SYTlMaUNrL0hURld5clViZkIKcUZiUTc4a1ZvRUQyNGNLRDU1MGpQQUVPMThSR2tnSHY5NzlJMndEZklINlgxN3U5Vk41dnFsdGN1ZzBzZlR4cQpVYk1KczEyc3VkK2pxMFdyL0RtbnlHS3k4b283b3pOYnByNThuenZZUFM1MkkxdzhUUmFqYUtwYW5WZldTdmRVCmgxUkdJZ3FIWFpWRnJ1ZEo2ZjF5Q3o2YzNERmxmQVVXQ2dyWmpTNFloZkRIU0ZHckVVTmhycEtaVTl0enp0dVkKTGRZK3I5WHpnRTNjZVZFQnNWdzdtMGZ0L3Nxd1BtVnViZkUxWVdOdCtpSCt1Q3JmVDhja3RjVHdhc1kxa3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: serveroperator-webhook-svc
      namespace: funcom-operators
      path: /validate-igw-funcom-com-v1-servergroup
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vservergroup.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - servergroups
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
