kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/databaseoperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/databaseoperator-serving-cert"},"name":"databaseoperator-validating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"databaseoperator-webhook-svc","namespace":"funcom-operators","path":"/validate-igw-funcom-com-v1-databaseoperation"}},"failurePolicy":"Fail","name":"vdatabaseoperation.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE","DELETE"],"resources":["databaseoperations"]}],"sideEffects":"None"}]}
  name: databaseoperator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: databaseoperator-webhook-svc
      namespace: funcom-operators
      path: /validate-igw-funcom-com-v1-databaseoperation
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vdatabaseoperation.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - databaseoperations
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
