kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: funcom-operators/databaseoperator-serving-cert
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from":"funcom-operators/databaseoperator-serving-cert"},"name":"databaseoperator-validating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"databaseoperator-webhook-svc","namespace":"funcom-operators","path":"/validate-igw-funcom-com-v1-databaseoperation"}},"failurePolicy":"Fail","name":"vdatabaseoperation.kb.io","rules":[{"apiGroups":["igw.funcom.com"],"apiVersions":["v1"],"operations":["CREATE","UPDATE","DELETE"],"resources":["databaseoperations"]}],"sideEffects":"None"}]}
  name: databaseoperator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lRTVVvWWFKeitDNGordWpZeVNkK3hsVEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTJNRGN5TlRBNE1qSXhOVm9YRFRJMk1UQXlNekE0TWpJeE5Wb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUDdXRGZteHBCaENKSFZEM1VGQncwYW9mT1ZuczQxbi9mUy9xdDE2CjB3cTNSdjdZRFphdlFSRVlwNmVhMjQ2S0FUK0pSMGhiMzZOMFZvZHBVYjhtSE5Qb0psekpXYWZPRlE5ZWk2a2UKekFzZXk1TDhxTlRxa0JCV2RUQjlEKzRjL0JQbU54blJ5Z3NQVEFQUWs3QmRieGJMb2U3bUtqL1U4ZDFBV1JPdQplWDBrOXAyS09yZFFteGRLTTY2QnJMSEE0OXMydER1M2piMUVSYzR6V0pETXhZc3hMbDRtWjlLOFBYTVA2UHRNCnNUbWRSTGNZUzZ1QldrRFZEcVNJcEVwdFljbHAxclpkY2g5eVc5b1diN3h4R3BOeUFLa3ljNmV5Z1Q4WnZ1S1kKT1RacjV1V3FZRkVaVmJ6R0NlRGdieXUzcXdyYWp4TVlZcExKOTFXbjR0NnV1SzhDQXdFQUFhT0JwRENCb1RBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBRENCZ0FZRFZSMFJBUUgvQkhZd2RJSXhaR0YwCllXSmhjMlZ2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE4yWXk1bWRXNWpiMjB0YjNCbGNtRjBiM0p6TG5OMlk0SS8KWkdGMFlXSmhjMlZ2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE4yWXk1bWRXNWpiMjB0YjNCbGNtRjBiM0p6TG5OMgpZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzdlV3FOK1hTWEpBbnZtU0hrCjhuQWxwOGZYM2phZHRCd1BLWGVZOCtCOWlYMGtyVCtpK3RyekFIbWhNaEFGS1NqSmxYdFhFQmdGaEZKWWNxYzkKdmVCR3B4T1V3Q3UzTnZUaHMzbnVUeSt2UkVNL0JqK0RQR05tVWx5cmQ5cXhJbWNWOWRpSWRKM1pITTNZd0pNdgo4azcwZW5rbDhhQzRIV3QrekhiQlFKNDRKVStBeXBjS1JNMnlLNHF1SGZSY3JhTDMxaWJEV3hHRzY3WFlLUUJwClE3UDZtNTRHVWpTOUdoZU0xQ21LQ2p0dkpwQ0w5YWQyNXNCbEZnWk43cHVPUW04RS82WFpQUTU0Nm1JTkdmeVEKWlAzZTRJb3ZGdTlKemppZmU0MjN6b1V1YmEwaktDRmNYV2NvckxrRzNXbVJIV1BPQzZqYVkyMXdpbUxGdndTUApRSVpUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: databaseoperator-webhook-svc
      namespace: funcom-operators
      path: /validate-igw-funcom-com-v1-databaseoperation
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vdatabaseoperation.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - igw.funcom.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - databaseoperations
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
